/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import javax.swing.JOptionPane;

/**
 *
 * @author Andrew
 */
public class añadirContacto extends javax.swing.JDialog{
    int x, y;
    /**
     * Creates new form añadirContacto
     */
    public añadirContacto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cajaTextoNombre = new javax.swing.JTextField();
        cajaTextoTelefono = new javax.swing.JTextField();
        cajaTextoCorreo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        añadirBoton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cerrarBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(289, 288));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cajaTextoNombre.setBackground(new java.awt.Color(255, 255, 255));
        cajaTextoNombre.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        cajaTextoNombre.setForeground(new java.awt.Color(0, 0, 0));
        cajaTextoNombre.setBorder(null);
        cajaTextoNombre.setOpaque(false);
        cajaTextoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaTextoNombreActionPerformed(evt);
            }
        });
        jPanel1.add(cajaTextoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 49, 180, 20));

        cajaTextoTelefono.setBackground(new java.awt.Color(255, 255, 255));
        cajaTextoTelefono.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        cajaTextoTelefono.setForeground(new java.awt.Color(0, 0, 0));
        cajaTextoTelefono.setBorder(null);
        cajaTextoTelefono.setOpaque(false);
        cajaTextoTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaTextoTelefonoActionPerformed(evt);
            }
        });
        jPanel1.add(cajaTextoTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 180, 20));

        cajaTextoCorreo.setBackground(new java.awt.Color(255, 255, 255));
        cajaTextoCorreo.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        cajaTextoCorreo.setForeground(new java.awt.Color(0, 0, 0));
        cajaTextoCorreo.setBorder(null);
        cajaTextoCorreo.setOpaque(false);
        cajaTextoCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaTextoCorreoActionPerformed(evt);
            }
        });
        jPanel1.add(cajaTextoCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 180, 20));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Nombre y Apellido");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 18, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Numero Telefonico");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 90, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Correo Electronico");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 162, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/txt_med.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/txt_med.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/txt_med.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        añadirBoton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        añadirBoton.setForeground(new java.awt.Color(255, 153, 204));
        añadirBoton.setText("Añadir +");
        añadirBoton.setBorderPainted(false);
        añadirBoton.setContentAreaFilled(false);
        añadirBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirBotonActionPerformed(evt);
            }
        });
        jPanel1.add(añadirBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 66, 290, 270));

        jPanel2.setBackground(new java.awt.Color(255, 153, 204));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Contacto nuevo +");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        cerrarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Archivos/cerrar_32px.png"))); // NOI18N
        cerrarBoton.setBorderPainted(false);
        cerrarBoton.setContentAreaFilled(false);
        cerrarBoton.setPreferredSize(new java.awt.Dimension(32, 32));
        cerrarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarBotonActionPerformed(evt);
            }
        });
        jPanel2.add(cerrarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 13, 42, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 289, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarBotonActionPerformed
        dispose();
    }//GEN-LAST:event_cerrarBotonActionPerformed

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void cajaTextoCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaTextoCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaTextoCorreoActionPerformed

    private void cajaTextoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaTextoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaTextoNombreActionPerformed

    private void cajaTextoTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaTextoTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaTextoTelefonoActionPerformed

    private void añadirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirBotonActionPerformed
        Archivos archivo = new Archivos();
        archivo.creaArchivo();
        
        String nombre, correo, celular;
        //Obtenemos los datos de las cajas de texto
        nombre = cajaTextoNombre.getText();
        celular = cajaTextoTelefono.getText();
        correo = cajaTextoCorreo.getText();
        //Creamos un objeto Contacto
        Contacto contacto = new Contacto(nombre, correo, celular);
        archivo.escribirTexto(contacto);
        cajaTextoNombre.setText("");
        cajaTextoCorreo.setText("");
        cajaTextoTelefono.setText("");

        dispose();
    }//GEN-LAST:event_añadirBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(añadirContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(añadirContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(añadirContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(añadirContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                añadirContacto dialog = new añadirContacto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton añadirBoton;
    private javax.swing.JTextField cajaTextoCorreo;
    private javax.swing.JTextField cajaTextoNombre;
    private javax.swing.JTextField cajaTextoTelefono;
    private javax.swing.JButton cerrarBoton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
